
- name: Install jq on Ubuntu
  block:
    - name: Install jq for Pakiti
      apt:
        name: "jq"
        state: present
        update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install jq on RL
  yum:
    name: "jq"
    state: present
  when: ansible_distribution == "Rocky"

- name: Copy in update_cloud_users script
  copy:
    src: "update_cloud_users.sh"
    dest: "/usr/local/sbin/update_cloud_users.sh"
    owner: root
    group: root
    mode: 0755


- name: Update cloud users periodically
  ansible.builtin.cron:
    name: "update_cloud_keys"
    minute: 0
    hour: 6
    job: "/usr/local/sbin/update_cloud_users.sh"
