- name: Stop wazuh-agent service
  become: true
  ansible.builtin.command:
    cmd: "systemctl stop wazuh-agent.service"

- name: Wazuh agent history
  file:
    path: "/var/ossec/etc/client.keys"
    state: absent
