
- name: Install cron on Ubuntu
  block:
    - name: Install cron for Pakiti
      apt:
        name: "cron"
        state: present
        update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install cron on RL
  yum:
    name: "cronie"
    state: present
  when: ansible_distribution == "Rocky"
