- name: Install wazuh on Ubuntu
  block:
    - name: Add GPG Key for Wazuh
      ansible.builtin.apt_key:
        url: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
        state: present

    - name: Add Wazuh repo
      ansible.builtin.apt_repository:
        repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
        state: present

    - name: Install Wazuh agent
      ansible.builtin.apt:
        name: wazuh-agent=4.8.1-1
        state: present
        update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install wazuh on Rocky
  block:
    - name: add wazuh repo
      yum_repository:
        name: wazuh
        file: wazuh
        description: "Repository to install wazuh"
        baseurl: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        enabled: true
        gpgcheck: false

    - name: Install wazuh
      yum:
        name:
          - wazuh-agent-4.8.1-1
        state: present
        disable_gpg_check: true
  when: ansible_distribution == "Rocky" and "ccm" not in ansible_facts.packages

- name: build wazuh groups list
  set_fact:
    wazuh_groups:
      - "cloud"
      - "{{ ansible_distribution | lower }}"
      - "{{ ansible_facts['os_family'] | lower}}"

- name: Copy wazuh client enrichment script
  copy:
    src: "wazuh/enrich-wazuh-agent.py"
    dest: "/var/ossec/bin/enrich-wazuh-agent.py"
    owner: root
    group: wazuh
    mode: 0750

- name: Copy wazuh drop in unit
  copy:
    src: "wazuh/preexec.conf"
    dest: "/etc/systemd/system/wazuh-agent.service.d/preexec.conf"
    owner: root
    group: root
    mode: 0644

- name: Copy wazuh config template
  copy:
    src: "wazuh/ossec.template"
    dest: "/var/ossec/etc/ossec.template"
    owner: root
    group: wazuh
    mode: 0750

- name: Update template file with groups
  replace:
    path: "/var/ossec/etc/wazuh.template"
    regexp: 'WAZUH_GROUPS'
    replace: "{{ wazuh_groups | join(',') }}"

- name: Enable wazuh-agent service
  become: true
  ansible.builtin.command:
    cmd: "systemctl enable wazuh-agent.service"

- name: Stop wazuh-agent service
  become: true
  ansible.builtin.command:
    cmd: "systemctl stop wazuh-agent.service"

- name: Wazuh agent history
  file:
    path: "/var/ossec/etc/client.keys"
    state: absent
