name: K8s Cluster API PR

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/capi_image_build.yaml"
      - "capi_image_builder/**"

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r capi_image_builder/requirements.txt

      - name: Run tests
        run: cd capi_image_builder && python3 -m pytest .

      - name: Analyse with pylint
        run: |
          cd capi_image_builder && pylint --recursive yes builder test
